# Generated by Django 4.0 on 2021-12-08 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=128, verbose_name='Nazwisko')),
                ('year_of_birth', models.DateField(verbose_name='Rok urodzenia')),
                ('year_of_death', models.DateField(help_text='opcjonalnie: jeżeli nie żyje', null=True, verbose_name='Rok śmierci')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=256, verbose_name='Tytuł')),
                ('year_of_publication', models.IntegerField(verbose_name='Rok publikacji')),
                ('publishing_house', models.CharField(max_length=256, verbose_name='Wydawnictwo')),
                ('genre', models.IntegerField(choices=[(1, 'klasyka'), (2, 'horror'), (3, 'kryminał'), (4, 'romans'), (5, 'literatura piękna'), (6, 'biografia'), (7, 'reportaż'), (8, 'poezja')], verbose_name='Gatunek')),
                ('review', models.TextField(null=True, verbose_name='Recenzja')),
                ('rating', models.IntegerField(choices=[(1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****')], verbose_name='Ocena')),
                ('author', models.ForeignKey(max_length=256, on_delete=django.db.models.deletion.CASCADE, to='czytaj.author', verbose_name='Autor')),
            ],
        ),
    ]
