# Generated by Django 4.0 on 2021-12-08 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('czytaj', '0003_alter_book_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='review',
        ),
    ]
