# Generated by Django 3.0.6 on 2021-12-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('czytaj', '0007_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='review',
            field=models.TextField(default=True, verbose_name='Recenzja'),
        ),
        migrations.AlterField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(to='czytaj.Book', verbose_name='Książki autora'),
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
