# Generated by Django 3.0.6 on 2021-12-09 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('czytaj', '0008_auto_20211209_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='review',
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(verbose_name='Recenzja')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='czytaj.Book', verbose_name='Książka')),
            ],
        ),
    ]
