# Generated by Django 4.0 on 2021-12-10 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('czytaj', '0009_auto_20211209_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='ScreenAdaptation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.CharField(max_length=64, verbose_name='Film')),
                ('director', models.CharField(max_length=64, verbose_name='Reżyser')),
                ('year_of_premiere', models.IntegerField(verbose_name='Rok premiery')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='czytaj.book', verbose_name='Książka')),
            ],
        ),
    ]
