# Generated by Django 4.0 on 2021-12-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('czytaj', '0013_userstory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(blank=True, null=True, to='czytaj.Book', verbose_name='Książki autora'),
        ),
    ]
