# Generated by Django 4.0 on 2021-12-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('czytaj', '0014_alter_author_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='tittle',
            field=models.CharField(default='', max_length=256, verbose_name='Tytuł recenzji'),
        ),
    ]
